esphome:
  name: ${name}
  friendly_name: ${friendly_name}

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name} Fallback Hotspot
    password: !secret ap_password

logger:

api:

captive_portal:

ota:
