substitutions:
  name: inverter
  friendly_name: Inverter
  uart_tx_pin: GPIO16
  uart_rx_pin: GPIO17

esp32:
  board: wemos_d1_mini32

packages:
  core: !include packages/core-local.yaml
  entities: !include packages/entities.yaml
  entities_48v: !include packages/entities-48v.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
