substitutions:
  inverter_maximum_power: "4500"
  name: inverter
  friendly_name: Inverter
  uart_tx_pin: GPIO1
  uart_rx_pin: GPIO3

esp32:
  board: d1_mini

packages:
  core: !include packages/core-local.yaml
  inverter: !include packages/inverter.yaml
  grid: !include packages/grid.yaml
  battery: !include packages/battery.yaml
  battery-24v: !include packages/battery-24v.yaml
  pv: !include packages/pv.yaml
  parallel: !include packages/parallel.yaml
  bms-24v: !include packages/bms-24v.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
