sensor:
  - platform: inv_8851
    bms_battery_current:
      name: "BMS battery current"
    bms_battery_soc:
      name: "BMS battery SOC"
    bms_battery_voltage:
      name: "BMS battery voltage"
    bms_cell_01_voltage:
      name: "BMS cell 01 voltage"
    bms_cell_02_voltage:
      name: "BMS cell 02 voltage"
    bms_cell_03_voltage:
      name: "BMS cell 03 voltage"
    bms_cell_04_voltage:
      name: "BMS cell 04 voltage"
    bms_cell_05_voltage:
      name: "BMS cell 05 voltage"
    bms_cell_06_voltage:
      name: "BMS cell 06 voltage"
    bms_cell_07_voltage:
      name: "BMS cell 07 voltage"
    bms_cell_08_voltage:
      name: "BMS cell 08 voltage"
    bms_cell_09_voltage:
      name: "BMS cell 09 voltage"
    bms_cell_10_voltage:
      name: "BMS cell 10 voltage"
    bms_cell_11_voltage:
      name: "BMS cell 11 voltage"
    bms_cell_12_voltage:
      name: "BMS cell 12 voltage"
    bms_cell_13_voltage:
      name: "BMS cell 13 voltage"
    bms_cell_14_voltage:
      name: "BMS cell 14 voltage"
    bms_cell_15_voltage:
      name: "BMS cell 15 voltage"
    bms_cell_16_voltage:
      name: "BMS cell 16 voltage"