esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "Inverter DTU"
  project:
    name: "lufton.esphome-inv-8851"
    version: 1.0.0
  libraries:
    - leodesigner/PowMr_4500_regmap

logger:
  level: VERY_VERBOSE
  logs:
    api: NONE
    api.connection: NONE
    api.service: NONE
    api.socket: NONE
    app: NONE
    captive_portal: NONE
    component: NONE
    esphome.ota: NONE
    gpio.output: NONE
    light: NONE
    logger: NONE
    mdns: NONE
    number: NONE
    safe_mode: NONE
    scheduler: NONE
    script: NONE
    select: NONE
    sensor: NONE
    text_sensor: NONE
    uart.arduino_esp32: NONE
    wifi: NONE

captive_portal:

uart:
  - id: inv_8851_uart
    baud_rate: 9600
    tx_pin: ${uart_tx_pin}
    rx_pin: ${uart_rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_hex(direction, bytes, ' ');

external_components:
  - source: components

inv_8851:
  version: ${version}
  update_interval: 5s
