esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:

captive_portal:

uart:
  - id: inv_8851_uart
    baud_rate: 9600
    tx_pin: ${uart_tx_pin}
    rx_pin: ${uart_rx_pin}

external_components:
  - source: components

inv_8851:
  update_interval: 5s
