binary_sensor:
  - platform: inv_8851
    battery_charging:
      name: "Battery charging"
    battery_connected:
      name: "Battery connected"
    bus_problem:
      name: "Bus problem"
    float_charging:
      name: "Float charging"
    grid_pll_problem:
      name: "Grid PLL problem"
    grid_power:
      name: "Grid power"
    parallel_lock_phase_problem:
      name: "Parallel lock phase problem"
    pv_excess:
      name: "PV excess"
    pv_input_problem:
      name: "PV input problem"
    system_power:
      name: "System power"

sensor:
  - platform: inv_8851
    battery_charge_current:
      name: "Battery charge current"
    battery_voltage:
      name: "Battery voltage"
    bms_battery_current:
      name: "BMS battery current"
    bms_battery_soc:
      name: "BMS battery SOC"
    bms_battery_voltage:
      name: "BMS battery voltage"
    bms_cell_01_voltage:
      name: "BMS cell 01 voltage"
    bms_cell_02_voltage:
      name: "BMS cell 02 voltage"
    bms_cell_03_voltage:
      name: "BMS cell 03 voltage"
    bms_cell_04_voltage:
      name: "BMS cell 04 voltage"
    bms_cell_05_voltage:
      name: "BMS cell 05 voltage"
    bms_cell_06_voltage:
      name: "BMS cell 06 voltage"
    bms_cell_07_voltage:
      name: "BMS cell 07 voltage"
    bms_cell_08_voltage:
      name: "BMS cell 08 voltage"
    bts_temperature:
      name: "BTS temperature"
    bus_voltage:
      name: "Bus voltage"
    fan1_speed_percentage:
      name: "Fan 1 speed percentage"
    fan2_speed_percentage:
      name: "Fan 2 speed percentage"
    grid_current:
      name: "Grid current"
    grid_frequency:
      name: "Grid frequency"
    grid_voltage:
      name: "Grid voltage"
    inverter_apparent_power:
      name: "Inverter apparent power"
    inverter_apparent_power_percentage:
      name: "Inverter apparent power percentage"
    inverter_current:
      name: "Inverter current"
    inverter_frequency:
      name: "Inverter frequency"
    inverter_power_percentage:
      name: "Inverter power percentage"
    inverter_software_version:
      name: "Inverter software version"
    inverter_voltage:
      name: "Inverter voltage"
    inverter_voltage_dc_component:
      name: "Inverter voltage DC component"
    load_apparent_power:
      name: "Load apparent power"
    load_current:
      name: "Load current"
    load_power:
      name: "Load power"
    log_number:
      name: "Log number"
    low_load_current:
      name: "Low load current"
    ntc2_temperature:
      name: "NTC2 temperature"
    ntc3_temperature:
      name: "NTC3 temperature"
    ntc4_temperature:
      name: "NTC4 temperature"
    parallel_current:
      name: "Parallel current"
    parallel_frequency:
      name: "Parallel frequency"
    parallel_voltage:
      name: "Parallel voltage"
    pv_current:
      name: "PV current"
    pv_power:
      name: "PV power"
    pv_voltage:
      name: "PV voltage"

select:
  - platform: inv_8851
    auto_return:
      name: "Auto return"
    backlight:
      name: "Backlight"
    battery_equalization:
      name: "Battery equalization"
    battery_type:
      name: "Battery type"
    buzzer:
      name: "Buzzer"
    charge_energy_priority:
      name: "Charge energy priority"
    fault_record:
      name: "Fault record"
    frequency:
      name: "Frequency"
    grid_voltage_range:
      name: "Grid voltage range"
    on_grid:
      name: "On grid"
    output_energy_priority:
      name: "Output energy priority"
    overload_restart:
      name: "Overload restart"
    overtemp_restart:
      name: "Overtemp restart"
    parallel_operation:
      name: "Parallel operation"
    phase:
      name: "Phase"
    power_buzzer:
      name: "Power buzzer"
    powersave_mode:
      name: "Powersave mode"

number:
  - platform: inv_8851
    battery_charge_cut_off_current:
      name: "Battery charge cut-off current"
      mode: box
      min_value: 2
      max_value: 20
      step: 0.1
    battery_equalization_interval:
      name: "Battery equalization interval"
      mode: box
      min_value: 0
      max_value: 90
      step: 1
    battery_equalization_time:
      name: "Battery equalization time"
      mode: box
      min_value: 5
      max_value: 900
      step: 1
    battery_equalization_timeout:
      name: "Battery equalization timeout"
      mode: box
      min_value: 5
      max_value: 900
      step: 1
    output_frequency:
      name: "Output frequency"
      mode: box
      min_value: 50
      max_value: 60
      step: 1
    output_voltage:
      name: "Output voltage"
      mode: box
      min_value: 100
      max_value: 240
      step: 1
