inv_8851:
  update_interval: 5s

binary_sensor:
  - platform: inv_8851
    battery_charging:
      name: "Battery charging"
    battery_connected:
      name: "Battery connected"
    bus_problem:
      name: "Bus problem"
    float_charging:
      name: "Float charging"
    grid_pll_problem:
      name: "Grid PLL problem"
    grid_power:
      name: "Grid power"
    parallel_lock_phase_problem:
      name: "Parallel lock phase problem"
    pv_excess:
      name: "PV excess"
    pv_input_problem:
      name: "PV input problem"
    system_power:
      name: "System power"

sensor:
  - platform: inv_8851
    battery_charge_current:
      name: "Battery charge current"
    battery_type:
      name: "Battery type"
    battery_voltage:
      name: "Battery voltage"
    bms_battery_current:
      name: "BMS battery current"
    bms_battery_soc:
      name: "BMS battery SOC"
    bms_battery_voltage:
      name: "BMS battery voltage"
    bms_cell_01_voltage:
      name: "BMS cell 01 voltage"
    bms_cell_02_voltage:
      name: "BMS cell 02 voltage"
    bms_cell_03_voltage:
      name: "BMS cell 03 voltage"
    bms_cell_04_voltage:
      name: "BMS cell 04 voltage"
    bms_cell_05_voltage:
      name: "BMS cell 05 voltage"
    bms_cell_06_voltage:
      name: "BMS cell 06 voltage"
    bms_cell_07_voltage:
      name: "BMS cell 07 voltage"
    bms_cell_08_voltage:
      name: "BMS cell 08 voltage"
    bms_cell_09_voltage:
      name: "BMS cell 09 voltage"
    bms_cell_10_voltage:
      name: "BMS cell 10 voltage"
    bms_cell_11_voltage:
      name: "BMS cell 11 voltage"
    bms_cell_12_voltage:
      name: "BMS cell 12 voltage"
    bms_cell_13_voltage:
      name: "BMS cell 13 voltage"
    bms_cell_14_voltage:
      name: "BMS cell 14 voltage"
    bms_cell_15_voltage:
      name: "BMS cell 15 voltage"
    bms_cell_16_voltage:
      name: "BMS cell 16 voltage"
    bts_temperature:
      name: "BTS temperature"
    bus_voltage:
      name: "Bus voltage"
    fan1_speed_percentage:
      name: "Fan 1 speed percentage"
    fan2_speed_percentage:
      name: "Fan 2 speed percentage"
    grid_current:
      name: "Grid current"
    grid_frequency:
      name: "Grid frequency"
    grid_voltage:
      name: "Grid voltage"
    inverter_apparent_power:
      name: "Inverter apparent power"
    inverter_apparent_power_percentage:
      name: "Inverter apparent power percentage"
    inverter_current:
      name: "Inverter current"
    inverter_frequency:
      name: "Inverter frequency"
    inverter_power_percentage:
      name: "Inverter power percentage"
    inverter_software_version:
      name: "Inverter software version"
    inverter_voltage:
      name: "Inverter voltage"
    inverter_voltage_dc_component:
      name: "Inverter voltage DC component"
    load_apparent_power:
      name: "Load apparent power"
    load_current:
      name: "Load current"
    load_power:
      name: "Load power"
    log_number:
      name: "Log number"
    low_load_current:
      name: "Low load current"
    ntc2_temperature:
      name: "NTC2 temperature"
    ntc3_temperature:
      name: "NTC3 temperature"
    ntc4_temperature:
      name: "NTC4 temperature"
    parallel_current:
      name: "Parallel current"
    parallel_frequency:
      name: "Parallel frequency"
    parallel_voltage:
      name: "Parallel voltage"
    pv_current:
      name: "PV current"
    pv_power:
      name: "PV power"
    pv_voltage:
      name: "PV voltage"
